module.exports = {
  ACCOUNT_LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
  ACCOUNT_CREDENTIALS_SUCCESS: 'ACCOUNT_CREDENTIALS_SUCCESS',
  ACCOUNT_CREATION_SUCCESS: 'ACCOUNT_CREATION_SUCCESS',
  ACCOUNT_VERIFICATION_EMAIL_SENT: 'ACCOUNT_VERIFICATION_EMAIL_SENT',
  ACCOUNT_VERIFICATION_SUCCESS: 'ACCOUNT_VERIFICATION_SUCCESS',
  FORGOT_PASSWORD_EMAIL_SENT: 'FORGOT_PASSWORD_EMAIL_SENT',
  FORGOT_PASSWORD_OTP_SUCCESS: 'FORGOT_PASSWORD_OTP_SUCCESS',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PROFILE_DETAIL_SUCCESS: 'PROFILE_DETAIL_SUCCESS',
  DEVICE_TOKEN_UPDATE_SUCCESS: 'DEVICE_TOKEN_UPDATE_SUCCESS',
  ACCOUNT_UPDATE_SUCCESS: 'ACCOUNT_UPDATE_SUCCESS',
};
