module.exports = Object.freeze({
  ASSET_ADDED_SUCCESS: 'ASSET_ADDED_SUCCESS',
  ASSET_UPDATE_SUCCESS: 'ASSET_UPDATE_SUCCESS',
  ASSET_GET_SUCCESS: 'ASSET_GET_SUCCESS',
  ASSET_DELETED_SUCCESS: 'ASSET_DELETED_SUCCESS',
  ASSET_RELEASE_SUCCESS: 'ASSET_RELEASE_SUCCESS',
});
