module.exports = Object.freeze({
  CONFIDER_REQUEST_SUCCESS: 'CONFIDER_REQUEST_SUCCESS',
  CONFIDER_GET_SUCCESS: 'CONFIDER_GET_SUCCESS',
  CONFIDER_UPDATE_SUCCESS: 'CONFIDER_UPDATE_SUCCESS',
  CONFIDER_DELETED_SUCCESS: 'CONFIDER_DELETED_SUCCESS',
  CONFIDER_REQUEST_GET_SUCCESS: 'CONFIDER_REQUEST_GET_SUCCESS',
  CONFIDER_ACCEPTED_GET_SUCCESS: 'CONFIDER_ACCEPTED_GET_SUCCESS',
  CONFIDER_REQUEST_ACCEPT_OR_REJECT_UPDATE_SUCCESS:
    'CONFIDER_REQUEST_ACCEPT_OR_REJECT_UPDATE_SUCCESS',
});
