module.exports = Object.freeze({
  DOVECHAT_POST_ADDED_SUCCESS: 'DOVECHAT_POST_ADDED_SUCCESS',
  DOVECHAT_POST_UPDATE_SUCCESS: 'DOVECHAT_POST_UPDATE_SUCCESS',
  DOVECHAT_POST_GET_SUCCESS: 'DOVECHAT_POST_GET_SUCCESS',
  DOVECHAT_POST_DELETED_SUCCESS: 'DOVECHAT_POST_DELETED_SUCCESS',
  DOVECHAT_POST_LIKE_SUCCESS: 'DOVECHAT_POST_LIKE_SUCCESS',
  DOVECHAT_POST_UNLIKE_SUCCESS: 'DOVECHAT_POST_UNLIKE_SUCCESS',
  DOVECHAT_POST_ADD_COMMENT_SUCCESS: 'DOVECHAT_POST_ADD_COMMENT_SUCCESS',
  DOVECHAT_POST_UPDATE_COMMENT_SUCCESS: 'DOVECHAT_POST_UPDATE_COMMENT_SUCCESS',
  DOVECHAT_POST_DELETE_COMMENT_SUCCESS: 'DOVECHAT_POST_DELETE_COMMENT_SUCCESS',
});
