module.exports = Object.freeze({
  GRANTEE_ADDED_SUCCESS: 'GRANTEE_ADDED_SUCCESS',
  GRANTEE_UPDATE_SUCCESS: 'GRANTEE_UPDATE_SUCCESS',
  GRANTEE_GET_SUCCESS: 'GRANTEE_GET_SUCCESS',
  GRANTEE_DELETED_SUCCESS: 'GRANTEE_DELETED_SUCCESS',
  GRANTEE_ASSET_GET_SUCCESS: 'GRANTEE_ASSET_GET_SUCCESS',
  GRANTEE_ASSET_VIEW_REQUEST_SUCCESS: 'GRANTEE_ASSET_VIEW_REQUEST_SUCCESS',
  GRANTEE_ASSET_VIEW_VERIFY_SUCCESS: 'GRANTEE_ASSET_VIEW_VERIFY_SUCCESS',
});
