module.exports = Object.freeze({
  VAULT_GET_SUCCESS: 'VAULT_GET_SUCCESS',
  VAULT_ASSET_DOWNLOAD_URL_SUCCESS: 'VAULT_ASSET_DOWNLOAD_URL_SUCCESS',
  VAULT_DELETED_SUCCESS: 'VAULT_DELETED_SUCCESS',
});
